## Problem 2a - Data manipulation (5 points)

Similarly as in earlier exercises the temperatures in our data are represented in Fahrenheit, hence,
you need to convert the temperatures into Celsius.


First, read again  the data from '6153237444115dat.csv' into a varaible `data` and split it into individual column variables (you can copy your code from problem 1 here):

In [26]:
# Import NumPy and read in data from csv

# YOUR CODE HERE
# raise NotImplementedError()
import numpy as np


# read the csv file
file = r"C:\Users\Gustavocolmenares\Documents\SchoolStaff\GIS_PCC\Courses_Training\Geo_python_Course\exercise_5\6153237444115dat.csv"

data = np.genfromtxt(file, delimiter=',', skip_header=1)
data

array([[2.84500000e+04, 9.99990000e+04, 2.01705010e+11, ...,
                   nan,            nan, 3.50000000e+01],
       [2.84500000e+04, 9.99990000e+04, 2.01705010e+11, ...,
                   nan,            nan,            nan],
       [2.84500000e+04, 9.99990000e+04, 2.01705010e+11, ...,
                   nan,            nan,            nan],
       ...,
       [2.99800000e+04, 9.99990000e+04, 2.01708312e+11, ...,
                   nan,            nan,            nan],
       [2.99800000e+04, 9.99990000e+04, 2.01708312e+11, ...,
                   nan,            nan, 0.00000000e+00],
       [2.99800000e+04, 9.99990000e+04, 2.01708312e+11, ...,
                   nan,            nan, 0.00000000e+00]])

**Remove no data values** (2 points)

In the codeblock below:

 - Create a new mask variable `tempmask` that is `True` for all finite temperature values, and `False` for `nan` values in the `temp` variable
 - Remove all rows from the column variables using the `tempmask` array

In [27]:
# define column temp from data
temp = data[:, 21]
station = data[:, 0]
# YOUR CODE HERE
# raise NotImplementedError()

# Create mask
tempmask = np.isfinite(temp)

In [28]:
# checkng data mask
print(temp[:500])
print(tempmask[:500])

[31. 30. 30. 31. 30. 30. 31. 30. 30. 31. 30. 30. 31. 30. 30. 31. 30. 30.
 31. 30. 30. 30. 30. 32. 32. 32. 34. 34. 34. 36. 37. 36. 37. 37. 37. 39.
 40. 39. 39. 41. 39. 41. 41. 41. 41. 42. 43. 43. 44. 43. 43. 43. 43. 43.
 42. 41. 41. 40. 39. 39. 38. 39. 37. 38. 37. 37. 37. 37. 36. 36. 36. 36.
 36. 36. 36. 36. 36. 36. 36. 36. 37. 37. 37. 37. 38. 37. 39. 39. 39. 39.
 41. 39. 41. 41. 41. 41. 43. 41. 41. 43. 43. 43. 45. 43. 41. 42. 43. 43.
 44. 39. 37. 39. 41. 39. 40. 39. 39. 40. 39. 39. 38. 37. 37. 38. 37. 36.
 37. 36. 36. 36. 36. 36. 36. 36. 34. 35. 34. 34. 34. 34. 34. 33. 34. 34.
 34. 36. 36. 35. 36. 36. 35. 36. 36. 36. 36. 36. 36. 36. 36. 36. 36. 37.
 37. 37. 37. 37. 37. 38. 37. 37. 39. 39. 37. 38. 37. 37. 38. 37. 37. 37.
 37. 37. 38. 37. 37. 38. 37. 37. 38. 37. 37. 38. 37. 37. 37. 37. 36. 37.
 36. 36. 35. 34. 34. 34. 32. 32. 32. 32. 32. 32. 32. 30. 31. 30. 30. 30.
 30. 30. 31. 30. 30. 31. 30. 30. 30. 30. 30. 31. 30. 30. 32. 32. 34. 35.
 36. 37. 40. 37. 39. 41. 41. 41. 44. 43. 43. 46. 43

In [29]:
# use the mask to remove all the 'nan' values from the temp column
good_temp = temp[tempmask == True]
good_temp
# compare length between tempmask and good_temp columns


array([31., 30., 30., ..., 64., 64., 64.])

In [39]:
# Check your data (for example using the len() function)



**Convert Fahrenheit to Celsius** (2 points)

- Create a new array variable `celsius` that converts `temp` to Celsius using the conversion formula (below)
 ![formula](../img/Fahrenheit_to_Celsius_formula.PNG)
 - Round the values in the `celsius` array to have 0 decimals (**don't** create a new variable --> update the current one)
 - Convert the `celsius` array values into integers (**don't** create a new variable --> update the current one)

In [30]:
# YOUR CODE HERE
# raise NotImplementedError()

celsius =  (good_temp - 32)/ (1.8)

In [31]:
# Check your data
print(temp[:6])
print(celsius[:6])


[31. 30. 30. 31. 30. 30.]
[-0.55555556 -1.11111111 -1.11111111 -0.55555556 -1.11111111 -1.11111111]


**Finalize your submission for Problem 2a** (1 point)
- Check that you have commented your code (add inline comments explaining what your code does)
- At this point, commit and push your changes to GitHub
- Was anything unclear to you until this point? Write your comments to the cell below.

YOUR ANSWER HERE


## Problem 2b - Data selection (5 points)

In this problem you should divide the data into separate subsets for different stations and save those arrays into csv files.

**Divide the data into two separate datasets:** (2 points)
  - Select all rows from the data arrays into variable called `kumpula` where the `station` value is `29980` using an array mask called `kmask`
  - Select all rows from the data arrays into variable called `rovaniemi` where the `station` value is `28450` using an array mask called `rmask`
  
Please use the given variable names and write your answer to the codeblock below.

In [43]:
# YOUR CODE HERE
# raise NotImplementedError()

# Create the masks to filter the data
kmask = station== 29980
rmask = station== 28450

# get shape of the new variables kumpula and rovaniemi
kumpula = data[kmask]
rovaniemi = data[rmask]

# print shape of the new arrays for kumpula and rovaniemi
print("kumpula:",kumpula.shape)
print("rovanemi:",rovaniemi.shape)

kumpula: (2924, 33)
rovanemi: (8770, 33)


In [39]:
# Check the data (you don't need to modify this cell)
print("Kumpula: \n", kumpula[:5,:], "\n")
print("Rovaniemi: \n", rovaniemi[:5,:], "\n")


Kumpula: 
 [[2.9980000e+04 9.9999000e+04 2.0170501e+11 2.0600000e+02 1.4000000e+01
  2.0000000e+01 7.2200000e+02           nan           nan           nan
            nan 2.7400000e+01           nan           nan           nan
            nan 0.0000000e+00           nan           nan           nan
  0.0000000e+00 3.7000000e+01 3.2000000e+01 1.0251000e+03           nan
  1.0219000e+03           nan           nan           nan           nan
            nan           nan 0.0000000e+00]
 [2.9980000e+04 9.9999000e+04 2.0170501e+11 1.9800000e+02 1.4000000e+01
  2.3000000e+01 7.2200000e+02           nan           nan           nan
            nan 2.9200000e+01           nan           nan           nan
            nan 0.0000000e+00           nan           nan           nan
            nan 3.7000000e+01 3.2000000e+01 1.0254000e+03           nan
  1.0222000e+03           nan           nan           nan           nan
            nan           nan 0.0000000e+00]
 [2.9980000e+04 9.9999000e+04 2.017

**Save the new arrays to csv files** (2 points)

- Save the `kumpula` array into a file called `Kumpula_temps_May_Aug_2017.csv` (CSV format) 
   - Separate the columns with a comma (`,`)
   - Use only 2 decimals in the floating point numbers
- Save the `rovaniemi` array into a file called `Rovaniemi_temps_May_Aug_2017.csv` (CSV format) 
   - Separate the columns with comma (`,`)
   - Use only 2 decimals in the floating point numbers

In [44]:
# YOUR CODE HERE
# raise NotImplementedError()
np.savetxt('kumpula_temps_May_Aug_2017.csv', kumpula, delimiter=',', fmt='%1.2f')
np.savetxt('Rovaniemi_temp_May_Aug_2017.csv', rovaniemi, delimiter=',', fmt='%1.2f')

**Commit and push changes (including the 2 csv files!) into your GitHub repository for Exercise 5** (1 point)

Did you encounter any problems with decimal formatting?

YOUR ANSWER HERE

Now you can continue to [problem 3: Data analysis](Exercise-5-problem3.ipynb)